#!/bin/bash
HOST='{FTP_SERVER}'
USER='{FTP_USER}'
PASSWD='{FTP_PASSWORD}'
curl http://127.0.0.1/helper.php > /home/pi/helper.php

ftp -n -v $HOST << EOT
ascii
user $USER $PASSWD
prompt
lcd /home/pi
cd htdocs
mput helper.php
bye
EOT

rm /home/pi/helper.php
